# Generated by Django 5.0.6 on 2024-06-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_categoria_producto_delete_alumno_delete_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='media/default.png', upload_to='img/'),
        ),
    ]
